### ISSUE TITLE
Cannot ReadStorageItemsAsync status: 400

### ISSUE THREAD

**Issue by Callepo** [suriyun-mmorpg/UnityMultiplayerARPG_DatabaseManager#2]
When using the DatabaseManager. when you try to go in game
Login with username and pw > Create character > press Start game. you are instantly disconnected, and server goes in a endless loop spamming Logs 
Cannot ReadStorageItemsAsync status: 400

This is with Sqlite, i didnt try mysql to know if its the same issue there also. but this only happens when using the DatabaseManager. i tried using normal way, works fine, tried using the Database Manager with server ran in editor, same issue, Server from Client build same issue, server with the mmo.Net build, same issue.

Every thing that uses sqlite  + Database Manager will crash with that spam

Cant find the issue yet. 
![image](https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_DatabaseManager/assets/7702658/a64190ad-a722-45ba-a68f-6496b49c432a)

**Comment by Callepo** [comment]
@insthync

**Comment by Callepo** [comment]
I commented out this code from Mapnetworkmanager and now my char is not stuck on loading anymore im ingame.
![image](https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_DatabaseManager/assets/7702658/68f3e953-331f-4591-9032-946fa9685cf6)

![image](https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_DatabaseManager/assets/7702658/d04cd5e1-6d9d-4c79-9cc9-5de1939c6df8)


so the Restdatabaseclient cant process that, there is an issue with that

By commented out that code, 
![image](https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_DatabaseManager/assets/7702658/ffb0f2e8-8f54-4b42-8765-8bde17422d10)

This is never called, which stops the Endless loop, where While(!succes), cuase the database never says succes, and it gets stuck in the while

**Comment by Callepo** [comment]
Hmm 
with the above code commented out, i can play the game, but when u logout, the map server log says this
![image](https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_DatabaseManager/assets/7702658/7e815551-9c29-444f-9e7d-aac1e221ebcd)

My character new location and any changes u did before logging off is not saved, u go back to orignal position

**Comment by insthync** [comment]
No log at database management service-side?

**Comment by Callepo** [comment]
@insthync none, the window console doesnt show anything, and no log file is produced in the project folder
![image](https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_DatabaseManager/assets/7702658/722787c5-05c0-4fe5-bdac-321f75b8cf14)

Tried changing the log level to debug and error to see if it shows anything, but nothing is shown

it just spams App _secret was succesfully authenticated in a loop.
![image](https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_DatabaseManager/assets/7702658/8bb4a250-64a0-444b-bb9e-4e4d5da4c17d)


While the map server spams the 400 error
![image](https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_DatabaseManager/assets/7702658/189a6e71-6b6c-4cc9-bf62-506dd3c07162)

**Comment by Callepo** [comment]
@insthync oh i got it now, 
![image](https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_DatabaseManager/assets/7702658/86fcc832-8656-46db-acc8-82d92de3b425)

**Comment by Callepo** [comment]
@insthync This is the log for the Update character Sync error
![image](https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_DatabaseManager/assets/7702658/fbd78729-8d99-41c7-97c5-e23acdc3a02e)

Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Infrastructure.ModelStateInvalidFilter (Order: -2000)

**Comment by insthync** [comment]
Fixed, you have to update this repo and also update [this one](https://github.com/insthync/unity-rest-client) too

**Comment by Callepo** [comment]
Works! Ty!

**Comment by Callepo** [comment]
@insthync the Storage is fixed but the Update Character Async is still there
maybe have to do the same with this message too.

![image](https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_DatabaseManager/assets/7702658/b97ac687-0ca9-4960-b1a6-5a3f5a566a51)

**Comment by Callepo** [comment]
@insthync 
![image](https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_DatabaseManager/assets/7702658/53915aa1-71d3-438a-82e3-90d585e3a9f8)
 yup this fixed it

**Comment by Callepo** [comment]
@insthync Made pull request

**Comment by insthync** [comment]
I've revert `RestClient` latest changes, it is not neccessary

**Comment by Callepo** [comment]
@insthync 
![image](https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_DatabaseManager/assets/7702658/5e86e5b5-70ee-494a-af14-cb6065370131)

When you start game, log out, press Start game again
Message pop up "Connection Rejected by server" 

On log out, accestoken is getting wiped

You have to click Logout, Go back all the way to Login Window, Relogin and than u get new accestoken and you can play again

**Comment by Callepo** [comment]
@insthync hmmm.. nvm, idk what happend, after 1 hour of trying to debug it, i turned server on and off, and now it works fine.. wtf?
