### ISSUE TITLE
Connection Rejected by server due to Accestoken

### ISSUE THREAD

**Issue by Callepo** [suriyun-mmorpg/UnityMultiplayerARPG_DatabaseManager#3]
@insthync 
![image](https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_DatabaseManager/assets/7702658/115478a8-f764-4016-880c-106690ff125f)

When 2 clients connected, this error is thrown in databasemanager Console

**Comment by Callepo** [comment]
https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_DatabaseManager/assets/7702658/5e12a662-be45-4e04-a7a5-e28c4f7ef787

![image](https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_DatabaseManager/assets/7702658/cb78ac7e-0a81-4b95-8eb0-b586750beffb)

**Comment by Callepo** [comment]
@insthync Tested with Mysql also, it throws the Invalid Acces Token there too, but obviously net the Nested transaction error from sqlite. it just shows acces token issue now.

Mysql DB
![image](https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_DatabaseManager/assets/7702658/20def3e5-fe70-4ca7-a4cd-1f57d9c1fe53)

**Comment by Callepo** [comment]
@insthync oh i should mention this is on a Server ( Linux Build) 
Local it happens also but not as easy.. you have to keep logging in/ logging out for a while, 2 accounts open and then it gets the error

[Local clients connected to local server]
![image](https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_DatabaseManager/assets/7702658/868d2a1c-718a-4503-aa09-e508e7e2f234)


IDK if 2 accounts is even the issue, but thats how i can reproduce it faster

**Comment by insthync** [comment]
Error log for mysql please

**Comment by Callepo** [comment]
@insthync when using mysql the databasemanager doesnt show any error like the SQLite did, just central creates a log file with acces token issue. ill try and debug it and see if i can catch an error

**Comment by Callepo** [comment]
@insthync The update user count throw the same error as the 2 other ones we fixed before where the value wasnt nullable
![image](https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_DatabaseManager/assets/7702658/bba54d49-8e5e-4131-85b9-7eacb2e053f9)

Ill see what else i can find

**Comment by Callepo** [comment]
@insthync 
![image](https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_DatabaseManager/assets/7702658/ec05de54-696f-4a36-8425-00e39f5c67ca)
![image](https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_DatabaseManager/assets/7702658/809a7aa0-4de4-4e74-90b8-9859416e27aa)

2nd one for Validate Acces Token

**Comment by Callepo** [comment]
same error again, so i think its null values

**Comment by Callepo** [comment]
@insthync 
ERROR RestDatabaseClient [2023-10-02 13:44:52] - Cannot UpdateCharacterAsync status: 500
ERROR MapNetworkManager(MapNetworkManager) [2023-10-02 13:45:12] - Invalid access token for user: 
ERROR No Tag [2023-10-02 13:45:22] - Can't deserialize content: , Newtonsoft.Json.JsonSerializationException: No JSON content found and type 'MultiplayerARPG.MMO.CharacterResp' is not nullable. Path '', line 0, position 0.
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) [0x000db] in <29e3dfd7379d434ca9881f8263fe42fe>:0 
  at Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00054] in <29e3dfd7379d434ca9881f8263fe42fe>:0 
  at Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00000] in <29e3dfd7379d434ca9881f8263fe42fe>:0 
  at Newtonsoft.Json.JsonConvert.DeserializeObject (System.String value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) [0x0002d] in <29e3dfd7379d434ca9881f8263fe42fe>:0 
  at Newtonsoft.Json.JsonConvert.DeserializeObject[T] (System.String value, Newtonsoft.Json.JsonSerializerSettings settings) [0x00000] in <29e3dfd7379d434ca9881f8263fe42fe>:0 
  at UnityRestClient.RestClient+Result`1[T]..ctor (System.Int64 responseCode, System.Boolean isHttpError, System.Boolean isNetworkError, System.String stringContent, System.String error) [0x00044] in <9ae98d53e4264ad78b3cc0b287e7ff7f>:0

**Comment by Callepo** [comment]
@insthync Rebuild all new again, test from the start
 
![image](https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_DatabaseManager/assets/7702658/4ad7d182-872b-46f7-aa9c-40d059db4bd7)


this is what central logs 
And this is databasemanager
![image](https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_DatabaseManager/assets/7702658/b451a74d-e824-4fd4-a1eb-f61c27235155)

Seems the process from db is going fine, its send okObjectsSesult back as a Response to client..

but the response is False.
 
![image](https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_DatabaseManager/assets/7702658/f50d2896-00a2-42e1-840c-215b561d0a25)

client is getting False. so player cant start game.. 

so the accestoken is being for some reason wiped or cant be read 


but in the DB
![image](https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_DatabaseManager/assets/7702658/eaf981d5-4d69-481d-83c0-b83e91691711)


its there.. so i thought it was maybe not caching properly so i put disabled caching on, and tried again.. it still giving the connection rejected from server. 

So i think the mapnetworkmanager is sending wrong assestoken to the db to be checked, or its putting the value as null
And when the db tries to validate it will be false.

**Comment by Callepo** [comment]
@insthync im debugging the client to see which Acces token its sending back to server and i noticed when you press Exit in game, game loads home scene, and prints out acces token 1 time.. 
But sometimes it prints it out 2 times in a row..

When it does this 2 times, thats when you get connection rejected
![image](https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_DatabaseManager/assets/7702658/880f3266-a05d-4a76-802e-273dd55cbea2)

Its sending 2 request to server OR server is processing the Exit 2 times and sending back 2 responses, and each process changes the token, so the 2nd change was on server making the token different than what the client has

**Comment by Callepo** [comment]
@insthync 



https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_DatabaseManager/assets/7702658/346aae18-3177-4f68-915a-aae1a3220f09

My Debug is inside OnCentralConnected 
![image](https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_DatabaseManager/assets/7702658/e45ef397-3396-47b8-a5ae-36598f768dbe)

**Comment by Callepo** [comment]
https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_DatabaseManager/assets/7702658/c97a9aa3-cef1-49c6-bd11-481fba8f3150

When logout, Db acces token is same as Debug log, when it print it out 2 times, when the connection rejected occurs..
The Db acces token is different from client

**Comment by Callepo** [comment]
@insthync

**Comment by Callepo** [comment]
Db manager get 2 request to validate acces token b2b, which makes it update the token in the db.
![image](https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_DatabaseManager/assets/7702658/c8f0306e-da24-4312-bd49-f318c1484302)

Look at the top and at the bottom, should only be 1 request and done. but Central server send 2 request, or Databasemanager thinks it got 2 for some reason

**Comment by Callepo** [comment]
@insthync ?

**Comment by insthync** [comment]
?

**Comment by insthync** [comment]
Did you find why `UIMmoSceneHome` -> `OnCentralServerConnected` called twice, all this problem is not because of database manager at all.

If you can't find it, then easiest way to fix it is just not update access token when validate access token, do it by delete `CentralNetworkManager_Login` -> `HandleRequestValidateAccessToken` -> `UpdateAccessTokenAsync`

**Comment by insthync** [comment]
When you write the access token log, did you try to find a difference from its stack trace ?

**Comment by insthync** [comment]
And you don't have to tag me, it is already notified and send me an email.

**Comment by Callepo** [comment]
> Did you find why `UIMmoSceneHome` -> `OnCentralServerConnected` called twice, all this problem is not because of database manager at all.
> 
> If you can't find it, then easiest way to fix it is just not update access token when validate access token, do it by delete `CentralNetworkManager_Login` -> `HandleRequestValidateAccessToken` -> `UpdateAccessTokenAsync`

removing it would fix the issue yes, but is there a specific reason why the accestoken was being changed everytime u press Exit ingame, instead only setting it once when u initially log in ?

And also this issue only happens when using the NET7 Services, not when running it the normal way. Even tho the same process is happening there.
And yes, i said either central is calling it twice, or db manager thinks its receiving it twice.
didnt fully know which one of the 2 it was precise.

**Comment by Callepo** [comment]
> When you write the access token log, did you try to find a difference from its stack trace ?

no i didnt. 
ill try and see if i can

**Comment by insthync** [comment]
> > Did you find why `UIMmoSceneHome` -> `OnCentralServerConnected` called twice, all this problem is not because of database manager at all.
> > If you can't find it, then easiest way to fix it is just not update access token when validate access token, do it by delete `CentralNetworkManager_Login` -> `HandleRequestValidateAccessToken` -> `UpdateAccessTokenAsync`
> 
> removing it would fix the issue yes, but is there a specific reason why the accestoken was being changed everytime u press Exit ingame, instead only setting it once when u initially log in ?
> 
> And also this issue only happens when using the NET7 Services, not when running it the normal way. Even tho the same process is happening there. And yes, i said either central is calling it twice, or db manager thinks its receiving it twice. didnt fully know which one of the 2 it was precise.

Because `OnCentralServerConnected ` is called twice, and in that function, it calls a function to validate the access token, and then when the validating it will change to a new access token, so the problem occurs.

**Comment by insthync** [comment]
You may include Time.framecount in the log message to see if it is being called in the same frame or not.

I think I will remove the update access token in the validate function because it is actually not necessary.

**Comment by Callepo** [comment]
> > > Did you find why `UIMmoSceneHome` -> `OnCentralServerConnected` called twice, all this problem is not because of database manager at all.
> > > If you can't find it, then easiest way to fix it is just not update access token when validate access token, do it by delete `CentralNetworkManager_Login` -> `HandleRequestValidateAccessToken` -> `UpdateAccessTokenAsync`
> > 
> > 
> > removing it would fix the issue yes, but is there a specific reason why the accestoken was being changed everytime u press Exit ingame, instead only setting it once when u initially log in ?
> > And also this issue only happens when using the NET7 Services, not when running it the normal way. Even tho the same process is happening there. And yes, i said either central is calling it twice, or db manager thinks its receiving it twice. didnt fully know which one of the 2 it was precise.
> 
> Because `OnCentralServerConnected ` is called twice, and in that function, it calls a function to validate the access token, and then when the validating it will change to a new access token, so the problem occurs.

Correct, i understand, But what would be the reason it only happens with the Net7 Services? 
cuase the same codes are there for the Unity Server too

And what was the original Reason the accestoken was set to change everytime we validate the token? was this needed for something?  and removing the update part would cuase an issue? or it was just done for no reason,

**Comment by Callepo** [comment]
> You may include Time.framecount in the log message to see if it is being called in the same frame or not.
> 
> I think I will remove the update access token in the validate function because it is actually not necessary.

ah ok ok, u already answered the Validate question here, cool, removing it would fix the issue we have tho yes

**Comment by insthync** [comment]
Maybe .Net service is faster and access token is changed before the next request.
